// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import path from "node:path";
import dotenv from "dotenv";
import { defineConfig, env } from "prisma/config";

dotenv.config({ path: path.resolve(__dirname, "../.env") });

export default defineConfig({
	schema: "./schema.prisma",
	migrations: {
		path: "../prisma/migrations",
	},
	datasource: {
		url: env("DATABASE_URL"),
	},
});
